# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='classes',
            new_name='caption',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
